name: Build Status - Development
on:
  push:
    branches:
    - development
  pull_request:
    branches:
    - development
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Branch Checkout
      uses: actions/checkout@v2.4.0
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build